#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "KOZAKI Tsuneaki"
email = "kozaki.tsuneaki@gmail.com"

[ui]
default-command = "log"
diff-formatter = [
    "difft",
    "--color=always",
    "--display=side-by-side-show-both",
    "$left",
    "$right"
]
editor = [
    "code",
    "--disable-workspace-trust",
    "--new-window",
    "--wait"
]

[remotes.origin]
auto-track-bookmarks = "*"
